export enum CallcenterMessage {
	'TRAIN_ENGINE_ADDED' = 'TRAIN_ENGINE_ADDED',
	'TRAIN_REGISTERED' = 'TRAIN_REGISTRED',
	'COUPLING' = 'COUPLING',
	'LOCOMOTIVE_ADDED' = 'LOCOMOTIVE_ADDED',
	'LOCOMOTIVES' = 'LOCOMOTIVES'
}

export enum ClientType {
	'CONTROL_CENTER',
	'REGISTRAR',
	'TRAIN'
}

export enum ClientEvent {
	'GET_TRAINS' = 'GET_TRAINS',
	'GET_TRAIN_ENGINES' = 'GET_TRAIN_ENGINES',
	'TRAIN_ENGINE_ADDED' = 'TRAIN_ENGINE_ADDED',
	'TRAINS' = 'TRAINS',
	'TRAIN_ENGINES' = 'TRAIN_ENGINES',
	'REGISTER_TRAIN' = 'REGISTER_TRAIN',
	'UPDATE_TRAIN' = 'UPDATE_TRAIN',
	'ENGINE_COUPLING_REQUEST' = 'ENGINE_COUPLING_REQUEST',
	'STATUS_UPDATE' = 'STATUS_UPDATE'
}

export enum LocomotiveStatus {
	'OFFLINE',
	'UNLINKED',
	'LINKED'
}

export enum RegistrarEvent {
	'TRAIN_REGISTERED' = 'TRAIN_REGISTERED'
}

export enum TrainEvent {
	'LINK' = 'LINK_TRAIN',
	'START' = 'START_TRAIN',
	'STOP' = 'STOP_TRAIN'
}

export enum TrainClientCallcenterRequest {
	'GET_LOCOMOTIVES' = 'GET_LOCOMOTIVES'
}

export enum TrainClientStatus {
	'OFFLINE' = 'OFFLINE',
	'WAITING_FOR_LOCOMOTIVES' = 'WAITING_FOR_LOCOMOTIVES',
	'READY' = 'READY'
}
